<Project>
  <!-- AUTHORITATIVE VRCL RELEASE VERSION. Update this value for the next release. -->
  <PropertyGroup>
    <VrclVersion>1.0.0-release-beta</VrclVersion>
    <VrclVersionNumber>1.0.0</VrclVersionNumber>
    <Version>$(VrclVersion)</Version>
    <AssemblyVersion>$(VrclVersionNumber).0</AssemblyVersion>
    <FileVersion>$(VrclVersionNumber).0</FileVersion>
    <InformationalVersion>$(VrclVersion)</InformationalVersion>
  </PropertyGroup>
</Project>
