<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <AssemblyName>VRCL Updater</AssemblyName>
    <RootNamespace>VRCLUpdater</RootNamespace>
    <ApplicationIcon>..\VRCL Client\vrcl_shell.ico</ApplicationIcon>
  </PropertyGroup>
</Project>